### ISSUE TITLE
Hourly Forecasts

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.JUL.PREP.3#1]
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

**Comment by elmar8287** [comment]
## Hourly Forecasts

- This task relates to making an investigation of API features and implementation on the Front-end
- By consolidating with our POD leader, we decided to implement not hourly, but daily forecasts.

The final version of the solution will look like below, considering of the Location chosen in input field (or automatically detected location in future):

<img width="740" alt="Screen Shot 2022-07-19 at 01 33 48" src="https://user-images.githubusercontent.com/49064106/179621377-615c4542-6716-496b-8516-a5b50e9d98a1.png">
