### ISSUE TITLE
Customized suggestions based on the weather 🛰️ of a place. 

### ISSUE THREAD

**Issue by somadisingh** [MLH-Fellowship/prep-project-22.JUL.PREP.3#17]
## When Users search for a place, they will also get suggestions like famous restaurants🍲, places of interest🏞️ or activities🏕️ which are prevalent during that particular season. 

# For example: 

- If the wind 🍃 speed of your location are below a certain threshold, you could go out to play badminton 🏸
- If you searched New York, and its summer ☀️ there, you will get activity suggestions and places of interest based on what's best in the summers 🌊
- If you search Japan or any city there, and its winter season ⛄ there, you will be suggested places with hot springs ♨️ to beat the winter chills 🥶

**Comment by somadisingh** [comment]
# Looking into potential APIs which could help in suggesting places. Narrowed down a few:
- Sygic Travel API
- OpenTripMap Places API
- GetYourGuide API
- Leezair Partner API
- Globaleur Content API: Suggests unique information such as themes & visit duration

**Comment by somadisingh** [comment]
##Update

@thucvy has suggested the use of Open AI API to fetch all the info regarding the activities and places of interest based on the weather and location. 
I will get down to calibrating the API configuration like the model best suited for our use case, the maximum amount of words displayed, the model temperature etc. and then we will start integrating the API into our application.

**Comment by thucvy** [comment]
> ##Update
> 
> @thucvy has suggested the use of Open AI API to fetch all the info regarding the activities and places of interest based on the weather and location. I will get down to calibrating the API configuration like the model best suited for our use case, the maximum amount of words displayed, the model temperature etc. and then we will start integrating the API into our application.

OpenAI API documentation can be found [HERE](https://beta.openai.com/docs/introduction).
Basically, OpenAI API will take "city" name and "weather" condition (variables) along with a proper prompt created in the backend as an input; and then provide answers based on that input prompt for a list of activities and attractions there are in that specific city during a certain weather condition. Example can be found in screenshot below:
![image](https://user-images.githubusercontent.com/93696226/180838433-d0444e2f-a7de-4913-9400-b95b952a3b0d.png)
In this example, some API configurations are:
- Model: text-curie-001
- Temperature: 0.7
- Max-tokens (max-length): 117
- Prompt: "provide a list of top 5 activities and attractions to do in New York as a local during winter season on a cloudy day"

**Comment by somadisingh** [comment]
Ideal Model Configuration:

- Model: text-curie-001
- Temperature: 0.86
- Max Length: Depending on the size of output which needs to be displayed on the website. Ideal range: 256 ~ 512 words
- Prompt: Top 5 activities to do in {Location} during {currentSeason}

**Comment by somadisingh** [comment]
Detailed prompt only works on Da Vinci model, since its the most powerful one available, but in order to control costs a normal prompt with Curie model is more than enough to achieve the goal.

**Comment by somadisingh** [comment]
## Update:

- Functionality has been implemented, only styling the output part remains
- App now uses GPT-3 AI API to suggest weather based activities.
- Kindly add the REACT_APP environment variable with the Open AI API key in `.env` file
- Fixed async error in component rendering
- API now suggests 5 activities based on the location and the current weather
- Model Prompt can be tweaked according to what the user wants, it can be changed to tourist destinations or hotspots
- Code has been integrated in App.js under `setState()` function, since keeping it in a different file would keep calling the API every time the user types in a letter, thus exceeding the upper limit of 150 requests/minute
- Please note that the AI model isn't perfect and might at times suggest generic activities independent of the weather & location
- API has limited credits hence comment out the API key while testing
- Temperature and Model can be experimented around with to get the desired answer
- API will only be called once a city name is detected

### Sample outputs:

![image](https://user-images.githubusercontent.com/78269625/181124147-ca8f09cc-a0d9-495c-bf49-4411c694bab1.png)

![image](https://user-images.githubusercontent.com/78269625/181124208-73e3e6ab-df4b-4c62-96f2-9003ad53ff7c.png)

![image](https://user-images.githubusercontent.com/78269625/181124228-62aa7af1-aee8-4dc3-bd2f-d8e52654fe4d.png)

![image](https://user-images.githubusercontent.com/78269625/181124255-8ccdbc8b-65cc-4257-b5c9-6ff35bea66c4.png)

**Comment by somadisingh** [comment]
## Update: Working and stats of the Activities recommendations:

- NPM package `openai-api` has been used to fetch the ai engine for sending and receiving the prompt
- Variables `Configuration` & `OpenAIApi` have been created to fetch the api key from `.env` file and create a new configuration containing model stats.
- `openai.createCompletion` method has been used to send prompt to the AI engine. 
- Prompt: `Top 5 activities to do in ${city} when its ${result.weather[0].main}:`
- `.then((response) => {});` method used to wait for the function to complete and then fetch the answers in a state variable.
- `activities` & `setActivities` state variables have been used to fetch and store the answer from the endpoint at `.JSON` file generated.

**Comment by somadisingh** [comment]
## Update 2

- Fixed the bug where activities card was not getting updated when selecting country in the Global Weather Map in issue #63 
- Indented the output
- Updated the design of activities card & applied glassmorphism

**Comment by somadisingh** [comment]
@thucvy the activities are not updating when clicking on a city on the 3D globe. Could you please work with @himanshu-thakur-7 on this issue and see if it can be resolved.
