### ISSUE TITLE
Change the colour scheme based on temperature / weather type

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.JUL.PREP.3#2]
Change the websites appearance to match the weather conditions. The Apple Weather app has some cool examples in iOS 15, check them out [here](https://9to5mac.com/2021/09/24/ios-15-weather-app-hands-on/).

**Comment by shehabadel** [comment]
We partially implemented the issue, now it looks like this
[386a5c6b-407f-432b-a99d-6e8d55ce3e31.webm](https://user-images.githubusercontent.com/53188087/179805376-00b3737c-dc49-4cf3-911e-e720541b2200.webm)
