### ISSUE TITLE
Replacing the world map with a 3D interactive Globe

### ISSUE THREAD

**Issue by himanshu-thakur-7** [MLH-Fellowship/prep-project-22.JUL.PREP.3#29]
I would like to propose to replace the current world map view for selecting countries with a 3D interactive Globe as shown here. 

I have implemented the basic UI for that here. 
https://github.com/himanshu-thakur-7/prep-project-22.JUL.PREP.3/tree/globe-dev
![Screenshot from 2022-07-22 14-01-55](https://user-images.githubusercontent.com/61612477/180398549-eacc5361-0a1b-4455-8ff7-58217effd5fa.png)
https://user-images.githubusercontent.com/61612477/180398145-148fea86-25e9-4e48-8927-4a1a19f60b70.mp4
Still have to put on the markers and make them selectable. Would love to collaborate with anyone interested.

**Comment by shehabadel** [comment]
Is there is supposed to be something here below `The forecast for the selected city` ?
@himanshu-thakur-7 @SanjaySinghRajpoot 
![image](https://user-images.githubusercontent.com/53188087/181067333-501ec406-c2a1-4d2f-92c5-8621ba3d8f9e.png)
