### ISSUE TITLE
Improve the UI and styling of the website

### ISSUE THREAD

**Issue by saswatsam786** [MLH-Fellowship/prep-project-22.JUL.PREP.3#37]
### UI improvements like:

- Improving the input area
- Fix the flickering issue between searching a particular country.
- Fix the world map(Decrease the size basically to improve scrolling through the website)
- Improve styling of the cards
- And many more

**If anyone wants to suggest some more. Please do suggest by commenting on this issue.**

**Comment by gibbonhug** [comment]
I will work on this. I am not sure what is meant by the 'flickering issue'. Did you mean the page getting shorter/taller when dragging the mouse across the map?

**Comment by saswatsam786** [comment]
> 

Actually, the page size gets changes when the data is shown and when it is not shown.

**Comment by somadisingh** [comment]
Did some changes in #66

**Comment by thucvy** [comment]
### Additional improvement
1. Add a second card (one that is similar to the new forecast card at the bottom below) to display air quality
2. Remove the original card (the white one that is at the top)
![image](https://user-images.githubusercontent.com/93696226/181514907-31a1b817-e66a-4590-8cd1-634693437ced.png)
3. Adjust the forecast card to be in the middle in small screen (improve responsiveness for this new forecast card)
