### ISSUE TITLE
Changing the project's font type

### ISSUE THREAD

**Issue by shehabadel** [MLH-Fellowship/prep-project-22.JUL.PREP.3#41]
![image](https://user-images.githubusercontent.com/53188087/180850627-b0feb25c-08d1-493a-ac94-3e2805af04c0.png)

We can change the font types used in the project to look more appealing. Instead of `Times New Roman`, we can use [Nuinto](https://fonts.google.com/specimen/Nunito) or [Roboto](https://fonts.google.com/specimen/Roboto)

**Comment by somadisingh** [comment]
Since another font type has been implemented, this issue is good to close
