### ISSUE TITLE
Add OpenAI API key as environment variable to Netlify

### ISSUE THREAD

**Issue by thucvy** [MLH-Fellowship/prep-project-22.JUL.PREP.3#52]
@wilkesalex could you please help add the _OpenAI API_ key as environment variable to Netlify so that the activities suggestion request based on the city (issue #17) can work on the live site. The variable name is `REACT_APP_OPENAI_API_KEY `(@somadisingh will provide you the key separately)

@somadisingh please provide Alex the _OpenAI API_ key separately to complete this exercise

**Comment by somadisingh** [comment]
Provided the OpenAI API key to @wilkesalex

**Comment by somadisingh** [comment]
Issue completed: The website is live and activities feature is working as intended.
