### ISSUE TITLE
Autocomplete for cities

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.JUL.PREP.3#6]
At the moment, when you type in a city, it won't help you finish your entry with suggestions. A cool feature would be if it had a drop down menu that suggested locations similar to the name. For example, if I type in `Cambridge`, it could tell me `Cambridge, MA, USA` or `Cambridge, UK` to help users get the right answers!

**Comment by himanshu-thakur-7** [comment]
Implemented & Merged into main repo
