### ISSUE TITLE
Fixing and modifying UI Components

### ISSUE THREAD

**Issue by shehabadel** [MLH-Fellowship/prep-project-22.JUL.PREP.3#71]
Need to fix the `input` text color instead of `white`.
![image](https://user-images.githubusercontent.com/53188087/181526372-845dc4b3-73f3-4fed-b26d-7c6658531e97.png)

In addition to decrease the `font-size` of the `Results`, and bring back the `weatherIcon`

**Comment by somadisingh** [comment]
It could be that netlify app had some configuration changes for font imports @awilkescom could you please look into it?

**Comment by awilkescom** [comment]
@somadisingh I dont think so, nothing changed for fonts on netlify I'm afraid

**Comment by somadisingh** [comment]
Yup, I think there's some bug inside. Thanks!
