### ISSUE TITLE
Celsius / Fahrenheit Toggle

### ISSUE THREAD

**Issue by gibbonhug** [MLH-Fellowship/prep-project-22.JUL.PREP.3#8]
Currently all temperatures are displayed with Celsius; this can be confusing for American users 🙂 It would be nice to allow the user to switch between C and F temperatures.

Perhaps we can automatically set the default unit based on the user's location once [Issue #3](https://github.com/MLH-Fellowship/prep-project-22.JUL.PREP.3/issues/3) is complete (ie, if they are detected to be in the US, the site defaults to Fahrenheit).

**Comment by somadisingh** [comment]
Successfully implemented by @gibbonhug & @dw2761 in issue #58 #64 

**FAHRENHEIT TOGGLE**
![image](https://user-images.githubusercontent.com/78269625/181450216-f22dd072-c1d8-4fd9-a397-d0c263cb7748.png)

**CELSIUS TOGGLE**
![image](https://user-images.githubusercontent.com/78269625/181450353-ab99b2b0-7ce0-49e6-9936-f8c52d15b99b.png)
